name: Deploy ERP Backend to dev
on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: Deploy to dev server
        uses: appleboy/ssh-action@master
        with:
          username: faheem
          host: ${{ secrets.DROPLET3 }}
          password: ${{ secrets.PASS }}
          script: 'cd ~ && ./server_deploy_ai-agent.sh'